### ISSUE TITLE
Cache poetry installation itself

### ISSUE THREAD

**Issue by Yajo** [abatilo/actions-poetry#36]
When using this action, it seems that poetry itself is installed through pip every time.

I wonder if it wouldn't be much faster and better if you just install it using [the official method](https://python-poetry.org/docs/#installation) with curl, that stores all poetry installation in `$HOME/.poetry`, and then set up cache automatically for that folder.

Next time you want to install it, it will be way faster because it is already installed from cache.

**Comment by abatilo** [comment]
Thanks for the suggestion @Yajo 

After experimenting with this in #37 two things became apparent to me.

1. By using `pip` we don't have to worry about which platform we're running on
2. Installing/downloading through `pip` only costs somewhere between 5-15 seconds. Since GitHub Action minutes are usually rounded up to the nearest minute, I'm not really sure if there's that much reason to go for the speed up.

If you disagree, please let me know! Otherwise, I'm going to close this issue.

**Comment by dmwyatt** [comment]
FWIW, this action takes around 30 seconds for me on `windows-latest`.

![image](https://user-images.githubusercontent.com/163359/128919825-2444ef14-803f-4413-a3fb-ea33ed921fff.png)

I care about this in one main situation that is not terribly uncommon for me:

When I'm actively working on my GitHub workflow and trying out different things...I have to wait the 30 seconds for every time make a change.

**Comment by threeal** [comment]
Hi, can we reopen this issue? I have another suggestion to caching the Poetry itself by installing it inside a virtual environment and caching the folder of that virtual environment, as described in [this documentation](https://python-poetry.org/docs/#ci-recommendations).
