### ISSUE TITLE
dependabot upgrades to version 3.7.4 of this GH-action

### ISSUE THREAD

**Issue by MisterRios** [abatilo/actions-poetry#56]
Hi-

This morning we received a notification to upgrade to version 3.7.4 of this action. I thought the numbering was weird, but the commits seemed to be legit.

However, our deploy failed because we use the `poetry-version` parameter. On closer inspection, it seems that dependabot is trying to upgrade to a `previous` version of poetry, since that version seems to have fewer commits (and is from 2019). 

As no official release has been made, I'm not sure why the `github-actions` package-ecosystem dependabot is doing this.  
See:
![Selection_719](https://user-images.githubusercontent.com/4686292/202658832-39cc3ba3-c354-4360-b349-9a0fd98cc0d8.png)
And:
![Selection_720](https://user-images.githubusercontent.com/4686292/202659237-bd20f5dd-d26e-4e09-93bf-d5a2a665b176.png)

**Comment by abatilo** [comment]
Hi all. Thanks for pointing this out. I don't know why dependabot decided now to change it's behavior but what seems to be happening is that dependabot is now also considering *branches* in its versioning and not just tags/releases. Way back when, this repo used to maintain multiple branches for setting up python and poetry on different versions of Python as its base in the Docker container when this was still a docker container (the v1 tags).

Sorry about that. I've deleted the branches entirely since they're no longer relevant and hopefully that sets everything straight.

**Comment by MisterRios** [comment]
Thanks for taking care of this so quickly!
